[package]
name = "rsrs"
version = "0.1.0"
authors = ["Evan Stoll <evanjsx@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.11"
serde = "1.0.89"
serde_derive = "1.0.89"
serde_json = "1.0.39"
log = "0.4.6"

[dev-dependencies]
env_logger = "0.6.1"
